### ISSUE TITLE
Consolidate Field Museum site records

### ISSUE THREAD

**Issue by rondlg** [fieldmuseum/EMu-Documentation#1004]
There are multiples. We want a single master record. This is what we have right now:

| irn | Department | Summary Data | Rank: (Political Details) | Centroid Latitude (DMS) | Centroid Longitude |
| --- | --- |  ---  |  --- | --- | --- | 
| 220135 | Mammals |North America, USA, Illinois, Cook Co, Chicago, Field Museum of Natural History | Precise Locality |  |  | 
| 220131 | Mammals | North America, USA, Illinois, Cook Co, Chicago, Field Columbian Museum. [LL] | Precise Locality | 41  47 25.569 N [41  47 25 N] | 87 34 57.537 [W  87 34 57 W] |
| 31646 | Botany | North America, USA, Illinois, Cook, Field Museum of Natural History. [LL] | Precise Locality | 41  51 58.11 N | 87 37 00.61 W |
| 483762	| Insects | North America, USA, Illinois, Cook, Chicago, Field Museum. [LL] | Precise Locality | 41  51 00.12 N | 87 39 00.19 W 
| **534514**	| **Insects** | **North America, USA, Illinois, Cook, Chicago, Field Museum of Natural History. [LL]** | **Precise Locality** |	**41  51 58.17 N**	| **87 37 01.14 W** |
| 481360	| Insects | North America, USA, Illinois, Cook, Chicago, Field Museum of Natural History. [LL] | Precise Locality  | 41  51 59.76 N | 87 37 08.02 W | 
| 481358	| Insects | North America, USA, Illinois, Cook, Chicago, Field Museum of Natural History. [LL] | Precise Locality | 41  52 01.29 N | 87 37 04.96 W |
| 481359 | Insects | North America, USA, Illinois, Cook, Chicago, Field Museum of Natural History. [LL]	| Precise Locality | 41  52 01.47 N | 87 36 58.45 W |
| 721095 | Insects | North America, USA, Illinois, Chicago, Field Museum | Precise Locality |  |  | 
| 338337 | Birds | North America, USA, Illinois, Cook, Chicago, Field Museum | Precise Locality |  |  |
| 320033 | Birds | North America, USA, Illinois, Cook, Chicago, Field Museum. [LL] | Precise Locality | 41  51 57.728 N | 87 37 00.666 W |
| 437547| Anthropology | North America, USA, Illinois, Cook, Chicago: The Field Museum | Precise Locality |  |  |

**Comment by rbaquiran** [comment]
Offer for main FMNH site record: 534514 
This was georeferenced by a very reliable staff member in 2018.

Three of Insect's Field Museum records actually pertain to sites outside of the museum building in the gardens or lawns for Bioblitz collecting, but that data was only represented in attached CE microhabitats.  
481358 - northwest lawn. Site edited to reflect this (record stays)
481359 - northeast lawn. Site edited to reflect this (record stays)
481360 - west side lawn. Site edited to reflect this (record stays)

Merged into 534514 until further decision made on which highlander survives:
721095 - in museum windows. Moved to CE microhabitat.
483762 - georeferenced by a less than reliable intern

**Comment by rondlg** [comment]
Using irn 534514 as the master gets my vote.

**Comment by wyattgaswick** [comment]
534514 works for me, though we should take Chicago out of Locality and make the master Chicago record the parent.

Here's the georeference circle, for reference. Works for me!
w


![temp](https://github.com/fieldmuseum/EMu-Documentation/assets/104448312/2de9bd44-9e9f-49dd-99fa-1fd934203316)

**Comment by rbaquiran** [comment]
Thanks, Wyatt. The parent of 534514 was corrected to Chicago and security switched to FMNH Master.

**Comment by rondlg** [comment]
Birds, Mammals and Anthropology records with no-cords merged into the master record

**Comment by rondlg** [comment]
We are left with:

| irn | Department | Source | Catalog | Summary Data | LatLon |
| -- | -- | -- | -- | -- | -- |
| 534514 | FMNH Master | GEOLocate | Insects | North America, USA, Illinois, Cook, Chicago, Field Museum of   Natural History. [LL] | 41  51 58.17 N |
| 31646 | Botany | GEOLocate | Botany | North America, USA, Illinois, Cook, Chicago, Field Museum of   Natural History. [LL] | 41  51 58.11 N |
| 320033 | Zoology | Topozone.com | Birds | North America, USA, Illinois, Cook, Chicago, Field Museum.   [LL] | 41  51 57.728 N |

@wyattgaswick Can the geoferencing information from Botany irn 31646  be copied into the Master Record (534514) ?

**Comment by rondlg** [comment]
Birds record is consolidated.

@wyattgaswick That just leaves the Botany record.

**Comment by wyattgaswick** [comment]
I don't have permissions to update all of the attached records (CEs at least), so someone else will have to do the merge & delete. I give my blessing though!

**Comment by rondlg** [comment]
@wyattgaswick if you can move the georeferencing information from the lat/lon tab on 31646 to a new row in 534514 I can so the merge

**Comment by wyattgaswick** [comment]
After a second look, I realized the georeferencing on 31646 isn't great....no error radius. The center points are very similar, so I don't think the 31646 coordinates are worth saving.

**Comment by rondlg** [comment]
Merge completed
