### ISSUE TITLE
ecollectionevents Topic 2: Bibliographic references fields

### ISSUE THREAD

**Issue by rondlg** [fieldmuseum/EMu-Documentation#176]
DISCUSSION POINTS:  

Too many duplicated reference/bibliography fields in the module. Consolidate and remove.

**Comment by rondlg** [comment]
DECISION(S): Move Collection 1 bibliographic references groupbox to Excavation Tab. Remove reference fields from Tables in the Terrestrial Tab

DATA CHANGES: No
[Data Changes Doc](https://docs.google.com/spreadsheets/d/1zLHEzm4J4g91PytnQGdo78XEO_Ns7AjI322aqfOrgN0/edit#gid=0)
Pre new development


Post development

**Comment by fmjjones** [comment]
Data changes made.
