### ISSUE TITLE
ecollectionevents Topic 11: Bioregion info - move from Sites to CE?

### ISSUE THREAD

**Issue by rondlg** [fieldmuseum/EMu-Documentation#185]
DISCUSSION POINTS:  

Nancy H [AC], 5 Nov 2018: 
About 10,000 RRC records have Bioregion info in Sites, but not in CollEvents where it should be. I think the agreement was:  If RRC/R.R.C. Catalog Record is linked to Coll_Event with “OtherNumbers” BLANK, and to Site Record with Biogeography/Region filled, move Sites:Biogeography data -> Coll_Event: Othernumbers.
(In some other cases, the data are in both fields and so don’t need attention; can be removed from Sites.) Fieldnames are: Move from Sites: LocSpecialGeographicUnit_tab (Biogeography/Region, on Political tab) to Coll_Events: ColOtherNumbers_tab, with ColOtherNumbersDescription_tab = Bioregion. This doesn’t have to happen immediately, but at least please save the data from Sites and its catalog attachment, before it gets wiped out of Sites. (If it does get wiped out of sites.)

**Comment by rondlg** [comment]
DECISION(S): 

Action Center Bioregion data moves to new “Additional Terrestrial Details” Description field where Kind = “Bioregion” 
DATA CHANGES: 
[Data Changes Doc](https://docs.google.com/spreadsheets/d/1zLHEzm4J4g91PytnQGdo78XEO_Ns7AjI322aqfOrgN0/edit#gid=0)
Pre new development
Post development: esites # 31

**Comment by rondlg** [comment]
@zkachian can you check that if this data cleanup task was ever completed?

**Comment by zkachian** [comment]
Sure thing, I will check with Nancy on this and I will let you know. Thanks for brining it to my attention.

**Comment by zkachian** [comment]
@rondlg I spoked with Nancy about this she said that she no longer needs this bioregion data anymore. I don't know whether or not the initial task was ever completed, but she no longer has a need for so she it ok with it being removed. If you need more info and if there is something we can help do to clean up, please let us know and we'll be happy to help.

**Comment by rondlg** [comment]
@zkachian As far as I can tell the BIOREGION was moved rom sites into CollectionEvents to the Other Numbers table (with Description = BIOREGION). I have replaced "BIOREGION" with "BIOREGION - Action Center RRC) so that in future we know what that refers to.

**Comment by zkachian** [comment]
@rondlg Thank you, Sharon! Is this all set now? I just want to make sure there isn't anything else we need to do for this right now.
