### ISSUE TITLE
ecollectionevents Topic 18: How to document Habitat measurements

### ISSUE THREAD

**Issue by rondlg** [fieldmuseum/EMu-Documentation#192]
DISCUSSION POINTS: 
New CE includes habitat measurement table for values & measurement types
Current CE doesn’t have that yet; use Habitat tab; Site Condition field

New Habitat tab:

![new_habitat_tab2](https://user-images.githubusercontent.com/702709/156624973-449952e1-b478-46c3-84bf-d8f56c60aba7.jpg)

**Comment by rondlg** [comment]
DECISION(S): 
Enter pipe-delimited measurements this way: 
[value] | [lookup list value]
e.g.:  75% | Percent Canopy Cover

DATA CHANGES: 
[Data Changes Doc](https://docs.google.com/spreadsheets/d/1zLHEzm4J4g91PytnQGdo78XEO_Ns7AjI322aqfOrgN0/edit#gid=0)
Pre new development: 
Post development:

**Comment by fmjjones** [comment]
No records left with pipe delimited values. Moving to done, but unformatted habitat data was not searched for. Further data cleaning may be necessary.
