### ISSUE TITLE
ebibliography Topic 1: Limiting number of types

### ISSUE THREAD

**Issue by rondlg** [fieldmuseum/EMu-Documentation#194]
DISCUSSION POINTS: 
We are limiting the number of “types” of Bibliographic records to mirror the development changes at NMNH.

**Comment by rondlg** [comment]
DECISION(S): 
We are using only Chapter, Book, Article, Journal, Manuscript, Other, Citation or Website. 
DATA CHANGES: We will move all records from the other types of records to one of the “approved” categories.
[Data Changes Doc](https://docs.google.com/spreadsheets/d/1pEyMm7J9t5wD9Xf3CZ6_VGBmFZloEtVLWviZ54OmAkE/edit?usp=sharing)
Pre new development: # 11 
Post development: None

**Comment by rondlg** [comment]
DECISION(S):
We are using only Chapter, Book, Article, Journal, Manuscript, Other, Citation or Website.
DATA CHANGES: We will move all records from the other types of records to one of the “approved” categories.
[Data Changes Doc](https://docs.google.com/spreadsheets/d/1pEyMm7J9t5wD9Xf3CZ6_VGBmFZloEtVLWviZ54OmAkE/edit?usp=sharing)
Pre new development: # 11
Post development: None

**Comment by fmjjones** [comment]
This decision has been superseded by the development of the BHL linking tool. Since BHL does not limit their types, we will not be limiting either.
