### ISSUE TITLE
Topic 11: Worldcat URL change (June 2019)

### ISSUE THREAD

**Issue by rondlg** [fieldmuseum/EMu-Documentation#204]
DISCUSSION POINTS: 

The URL changed from:
https://fieldmuseumlibrary.worldcat.org/ to https://fieldmuseumlibrary.on.worldcat.org/
The OCLC numbers remain the same. I don't know how many users this would impact, if any. I made a group in Bib, called New_Worldcat_Link and the three of you are in Security tab. There are 9 in Multimedia that I'd made (again pre-standards) and I think I know how to correct those (meaning I made 'em, happy to fix 'em). To illustrate, take a look at MM irn 1411438 (Chinese Birds, Carolyn Toren has them as her desktop wallpaper) and the Worldcat entry in the Bib Tab.

**Comment by rondlg** [comment]
This is from ZD ticket: 37768

Need to work through data changes if any.

**Comment by fmjjones** [comment]
Remaining Bibliography record urls were updated 4 mar 2022.

**Comment by fmjjones** [comment]
Moved to pending dev. Additional data changes required to move urls currently in Notes to Website Identifier field post development.
