### ISSUE TITLE
Cleanup/Merge California Counties Butte and El Dorado

### ISSUE THREAD

**Issue by rondlg** [fieldmuseum/EMu-Documentation#490]
There are duplicate county site records for: 

**- USA-California-El Dorado**
| Catalog | irn | Master |
| --- | --- | --- |
| Insects | 399606 | No |
| Botany | 620060 | No |
| Technology | 700142 | Yes |
| Anthropology | 420578 | ??? |

**- USA-California-Butte County**
| Catalog | irn | Master |
| --- | --- | --- |
| Anthropology | 420534 | ??? |
| Botany | 571009 | Yes |

that need to be merged. There are 2 groups shared with all users:

- esites cleanup - Butte County
- esites cleanup - El Dorado

Departments should pick a master record from the set and merge into it.

Generated from - https://fieldmuseum.zendesk.com/agent/tickets/54358

**Comment by rbaquiran** [comment]
@rondlg Just a note Sharon, these two lists are mismatched with their locality names. The first batch is El Dorado and second is Butte. Insects has merged ours with Technology's 700142 as master for El Dorado.

**Comment by rondlg** [comment]
Ha - called out by Beka!

**Comment by rbaquiran** [comment]
No worries! Thank you for all the work you do herding us cats!

**Comment by wyattgaswick** [comment]
For El Dorado county, I merged the Botany record into the Technology record (700142).

I vote to keep & merge into the Botany record for Butte county (571009) because it has proper geolocated coordinates. 

...and for pretty much any US county, I will vote to keep the record with lat/long/radius geolocation data, or at least copy that data over into whichever record is being kept.

**Comment by rbaquiran** [comment]
Insects seconds this lat/long/radius preference, by the way.

**Comment by CPhilippField** [comment]
Jamie and Chris updated El Dorado county - did same on Butte, however for an undetermined set of records received a message that we did not have permissions to update all / certain records

**Comment by rondlg** [comment]
There were 4 bird catalogue/collectionevents using 420534. They are now updated to use 571009.

### Final status: 

**- USA-California-El Dorado**
| Catalog | irn | Master |
| --- | --- | --- |
| Insects | 399606 | Deleted |
| Botany | 620060 | Deleted |
| Technology | 700142 | Yes |
| Anthropology | 420578 | Deleted |

**- USA-California-Butte County**
| Catalog | irn | Master |
| --- | --- | --- |
| Anthropology | 420534 | Deleted |
| Botany | 571009 | Yes |
