### ISSUE TITLE
esites Topic 54: precise locality character limit

### ISSUE THREAD

**Issue by rondlg** [fieldmuseum/EMu-Documentation#54]
DISCUSSION POINTS: 

Will there be a character limit in the precise locality field? If so, what will it be? 

Thanks. So it will be 451 characters? Rudiger is composing info for those fields on a spreadsheet offline, and he wants to know if he should work to a limit. To be clear, this is regarding what the limit will be once the bug is resolved. 

See also EMu-hour Q&A 2021 # 42

**Comment by rondlg** [comment]
DECISION: 

For now yes. It is 81 characters, there is a note in the field help that this is a known bug and the next release will have the limit set to be the same as the old field. If it is longer then put the full string into the Verbatim field which is longer.

**Comment by rondlg** [comment]
JIRA #339

**Comment by rondlg** [comment]
DATA CHANGES: [Data Changes Doc](https://docs.google.com/spreadsheets/d/1gqrciOw-ATgI4MqS5727f0CTvDohP_XJDvfONGpCT0E)
Pre new development:
Post development: #73

**Comment by fmjjones** [comment]
Fixed in version 2204151.

**Comment by rondlg** [comment]
See also: https://github.com/fieldmuseum/EMu-Documentation/issues/17
