### ISSUE TITLE
esites: Cleanup/Merge Galapagos records [Ecuador] Island group - TASK 2

### ISSUE THREAD

**Issue by rondlg** [fieldmuseum/EMu-Documentation#573]
### TASK 2: Cleanup the Island Group records

Notes:
- EMu group = "esites cleanup - Galapagos Island group"
-  Use spelling with diacrits. 

Recommendations:
- ** NEED TO CHOOSE ONE AND MERGE** 630915 has diacrits 

***

| irn | SummaryData | PolPoliticalRank | Departments | Master |
| --- | --- | --- | --- | --- |
| 630918 | South America, Ecuador, Galápagos, Galapagos Islands | Island Group | IZ | ? |
| 630915 | South America, Ecuador, Galápagos, Galápagos Islands | Island Group | Herps-Botany-Fishes-IZ | ?|
| 630917 | South America, Ecuador, Galápagos, Galapagos Islands | Island Group | Botany-Fishes-IZ | ? |

**Comment by Amiacalva** [comment]
Agree with Wyatt.  Keep 630915.  Fishes has moved to that IRN.

**Comment by Amiacalva** [comment]
Fishes is ok with whichever is picked.  630917 now has diacrits also.  They look pretty identical.

**Comment by rondlg** [comment]
**DECISION: irn 630915 selected as the master record.**
- 630917 and 6309178 merged into 630915 and deleted
