### ISSUE TITLE
esites: Consolidate Pago Pago site records

### ISSUE THREAD

**Issue by rondlg** [fieldmuseum/EMu-Documentation#611]
# TASK: Consolidate Pago Pago city records

Notes: There are currently 2 parent records for the "city" Pago Pago in Samoan Islands. Proposal is to use the Anthropology record as the master.

## Pago Pago
| irn | SummaryData | PolPoliticalRank | Departments | Master |
| --- | --- | --- | --- | --- |
| 709470 | Oceania, American Samoa, Tutuila, Eastern, Pago Pago | City | Invertebrate Zoology | ? |
| 646149 | Pacific, Samoan Islands, Tutuila Island, American Samoa, Pago Pago: Pago Pago | City | Anthropology | Yes |

**Comment by seanmkeogh** [comment]
The Anthropology site record (646149) is a 'Cultural' Record Classification. Ours (709470) is 'Terrestrial'. Is this a problem? Would Anthropology be willing to change their Record Classification to 'Terrestrial' before merging?

**Comment by rondlg** [comment]
@seanmkeogh the Terrestrial/Cultural classification only affects the summary string, so for sites in the Pacific region we use the term "Pacific" Not "Oceania" as it is more culturally appropriate. This does not affect your ability list oceania as the continent for your terrestrial (or aquatic) records. Anthro has a very large Pacific collection so if you don't mind it would be better to merge into the cultural record. Can you check in with Chris Phillip in Anthro?

**Comment by seanmkeogh** [comment]
Merged IRN 709470 into 646149 and deleted 709470.
