### ISSUE TITLE
eparties: Clean up Ayer eparties records

### ISSUE THREAD

**Issue by rondlg** [fieldmuseum/EMu-Documentation#848]
### Discussed in https://github.com/fieldmuseum/EMu-Documentation/discussions/847

<div type='discussions-op-text'>

<sup>Originally posted by **rondlg** June 16, 2023</sup>
Description: Update the Mrs. E.E. Ayer Anthro Parties record (irn 403262) to include her first, middle, and maiden name: Emma Augusta Burbank Ayer and change it to FMNH master? OR better yet merge this info and record into her Botany Parties record (irn 25762) and make it an FMNH master? There's a second Botany Parties record (irn 1112) for her that could be merged into these.   
Merge the Edward Ayer records into one FMNH master (irn 107057)? (The other irns include: 99782, 146300, 403171, and 99897.) This might be a heavier lift to accomplish since these Party records are likely attached to MANY records in other modules.

| irn | NamFirst | NamMiddle | NamLast | NamSource | ColCollaborationName | STATUS |
| -- | -- | -- | -- | -- | -- | -- |
| 99897 | E | E | Ayer | Mammals Master |  | Merged |
| 99782 | E |   | Ayer | Mammals Master |  | Merged |
| 403262 | E. | E. | Ayer | Anthro Master |  |  |
| 1112 | E. | E. | Ayer | Botany Master |  |  |
| 403171 | Edward | A. | Ayer | Anthro Master |  |  |  
| 157125 | Edward | C. | Ayer | Invertebrate Zoology Master |  | Merged |
| 146300 | Edward | E | Ayer | Paleobotany, Geology Master |  |  |
| 403261 | Edward | E. | Ayer | FMNH Master |  | MASTER |
| 25762 | Emma | B. | Ayer | Botany Master |  | MASTER  |
| 31260 | François |   | Ayer | Botany Master |  | MASTER |
| 8088 |   |   |   | Birds Master | J Borden & E E Ayer |  Updated |
| 401610 |   |   |   | Anthro Master | Ayer, Emma B. - Estate |  |
| 195253 |   |   |   | Anthro Master | H.N. Higinbotham and E.E. Ayer |  |

</div>

**Comment by kjakymec** [comment]
IZ merged into record 403261.

**Comment by rondlg** [comment]
| irn | Party Type | Source | Title | FullName | First | Middle | Last | Organisation: (Organisation   Details)/Organisation: (Herbarium Information) | Summary Data | Notes |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
| 403262 | Person | Anthro Master | Mrs. | Mrs. Emma A. B. Ayer | Emma | Augusta Burbank | Ayer |   | Mrs. Emma A. B. Ayer |   |
| 146300 | Person | Paleobotany, Geology Master | Mr. | Mr. Edward E. Ayer | Edward | E | Ayer |   | Mr. Edward E. Ayer | Mr Edward E Ayer | |
| 403261 | Person | FMNH Master |   | Edward E. Ayer | Edward | Everett | Ayer | Field Columbian Museum [FCM] | Edward E. Ayer : Field Columbian Museum [FCM] |   |
| 25762 | Person | Botany Master | Mrs. | Mrs. Emma B. Ayer | Emma | Burbank | Ayer |   | Mrs. Emma B. Ayer | Person's name from original data: Full name arc |

**Comment by rondlg** [comment]
@wyattgaswick @cmaves3 @lhancockFM 

This task is almost complete. We have 2 Emma's and 2 Edward's left...

- Edward: 403261 is the master record. Geology folks please merge into it.
- Emma:  We have 25762 and 403262. Anthro and Botany can you pick one and then merge as necessary please.

**Comment by wyattgaswick** [comment]
The Botany record (25762) has a bunch of biography, external refs, etc so I'd so that's the one to merge into. I went ahead and added the additional middle name (Augusta) from the Anthro record to the Botany one, so I think it's ready to merge (but anthro maybe double-check to be sure)

**Comment by lhancockFM** [comment]
The Anthro record has her full name as Mrs. Emma Augusta Burbank Ayer. If I
can add Augusta to the Botany record, I'm happy to merge everything into
that one.

Lauren Hancock
Head Registrar, Anthropology Collections
(she/her/hers)

Field Museum
1400 S. DuSable Lake Shore Drive
Chicago, IL  60605
312.665.7872

http://collections-anthropology.fieldmuseum.org/

*I acknowledge that I live and work on the traditional homelands of the **Three
Fires Confederacy: Bodéwadmik (Potawatami), Anishinaabeg (Ojibwe), **and
Odawak (Odawa), and of the Hoocąk (Ho'Chunk/Winnebago), Inoka (Illini
**Confederacy),
Kiash Matchitiwuk (Menominee), Kiikaapoi (Kickapoo), **Myaamiaki (Miami),
Meshkwakîha (Meskwaki), Asâkîwaki (Sauk), Jiwere (Otoe), **Nutachi
(Missouria), and Baxoje (Iowas). I recognize and respect the many Native
people who have called and continue to call Chicago home. *



<http://fieldmuseum.org>

**Comment by lhancockFM** [comment]
Done!

Lauren Hancock
Head Registrar, Anthropology Collections
(she/her/hers)

Field Museum
1400 S. DuSable Lake Shore Drive
Chicago, IL  60605
312.665.7872

http://collections-anthropology.fieldmuseum.org/

*I acknowledge that I live and work on the traditional homelands of the **Three
Fires Confederacy: Bodéwadmik (Potawatami), Anishinaabeg (Ojibwe), **and
Odawak (Odawa), and of the Hoocąk (Ho'Chunk/Winnebago), Inoka (Illini
**Confederacy),
Kiash Matchitiwuk (Menominee), Kiikaapoi (Kickapoo), **Myaamiaki (Miami),
Meshkwakîha (Meskwaki), Asâkîwaki (Sauk), Jiwere (Otoe), **Nutachi
(Missouria), and Baxoje (Iowas). I recognize and respect the many Native
people who have called and continue to call Chicago home. *



<http://fieldmuseum.org>

**Comment by rondlg** [comment]
@wyattgaswick @lhancockFM Thankyou.

@cmaves3 all you on the geology front!

**Comment by cmaves3** [comment]
Merge took its time but Geo is done.
