### ISSUE TITLE
esites: Cleanup Bolivia department records

### ISSUE THREAD

**Issue by rondlg** [fieldmuseum/EMu-Documentation#881]
# Master Records
| irn | Department | SummaryData | Rank | 
| --- | --- | --- | --- |
| 1073 | FMNH Master | South America, Bolivia, Cochabamba. [LL] | Department | 
| 326 | FMNH Master | South America,   Bolivia, Chuquisaca. [LL] | Department | 
| 1062 | FMNH Master | South America,   Bolivia, Beni. [LL] | Department | 
| 1092 | FMNH Master | South America,   Bolivia, Pando. [LL] | Department | 
| 1099 | FMNH Master | South America,   Bolivia, Santa Cruz. [LL] | Department | 
| 1103 | FMNH Master | South America,   Bolivia, Tarija. [LL] | Department | 
| 22668 | FMNH Master | South America,   Bolivia, La Paz. [LL] | Department | 
| 40569 | FMNH Master | South America,   Bolivia, Potosí. [LL] | Department | 
| 44898 | FMNH Master | South America,   Bolivia, Oruro. [LL] | Department | 

# Records to be checked
| irn | Department | SummaryData | Rank | Status |
| --- | --- | --- | --- | --- |
| 697246 | Botany | South America,   Bolivia, Ichilo | pd2 |  Merged  |
| 633795 | Insects Zoology | South America,   Bolivia, Cercado | pd2 | Merged |
| 633794 | Insects Zoology | South America,   Bolivia, Benin | pd2 | Merged |
| 633801 | Insects Zoology | South America,   Bolivia, Vaca Diez | pd2 | Merged |
| 633798 | Insects Zoology | South America,   Bolivia, Nuflo De Chavez | pd2 | Merged |
| 349669 | Amphibians and   Reptiles Zoology | South America,   Bolivia, Beni Region | pd2 | Merged |
| 633800 | Amphibians and   Reptiles Zoology | South America,   Bolivia, Sara | pd2 | Merged |
| 633792 | Invertebrate   Zoology Zoology | South America,   Bolivia, Amazonica | pd2 | Merged |
| 697244 | Invertebrate   Zoology Zoology | South America,   Bolivia, Chiquitos | pd2 | Merged |
| 633796 | Invertebrate   Zoology Zoology | South America,   Bolivia, De Sara | pd2 | Merged |
| 205747 | Invertebrate   Zoology Zoology | South America,   Bolivia, El Beni. [LL] | pd2 | Merged |

**Comment by wyattgaswick** [comment]
697246 is merged with with the proper pd3 record & deleted

**Comment by jmata8895** [comment]
IRNs 349669 and 633800 are now merged with the proper FMNH masters and have been deleted!

**Comment by rbaquiran** [comment]
633795 merged into 699080 and deleted
633794 merged into 1062 and deleted
633801 merged into 706648 and deleted
633798 merged into 711398 as much as I could, but the following irns need this change: Botany Catalog irn 4573789 and CE irn 3611252
Thanks!

**Comment by wyattgaswick** [comment]
Ok, Botany followup - 633798 merged into 711398 and deleted. Thanks!

**Comment by seanmkeogh** [comment]
IZ pd3s merged with Master Departments and deleted
