### ISSUE TITLE
Updated Staff/Contact lists for Collections search websites

### ISSUE THREAD

**Issue by rondlg** [fieldmuseum/EMu-Documentation#979]
For collections websites – Please add updated lists here. There will be a section on the homepage that you should look at. So far we have:

1. https://collections-anthropology.fieldmuseum.org/
2. https://collections-botany.fieldmuseum.org/
3. https://collections-geology.fieldmuseum.org/
4. https://collections-zoology.fieldmuseum.org/

**Comment by rondlg** [comment]
From Botany
2. https://collections-botany.fieldmuseum.org/
- Kimberly Hansen, Collections Manager Flowering Plants
- Yarency Rodriguez, Collections Assistant II
- Note: Maria Kawasaki is [Lucia Kawasaki](mailto:lkawasaki@fieldmuseum.org)(but I guess this is drawn from the web - so this is an HR issue?)
- Wyatt Gaswick is listed as Research Assistant II, but he is Collections Assistant III
- [Todd Widhelm](mailto:twidhelm@fieldmuseum.org) is listed as Collections Manager should be Collections Manager, Mycology and Lichenology

**Comment by rondlg** [comment]
From Invertebrates:
4a. https://collections-zoology.fieldmuseum.org/
- Invertebrates - Sean Keogh

**Comment by chungkamei** [comment]
Department of Amphibians & Reptiles
Collections Staff:
1. Rachunliu G. Kamei, Collections Manager, Amphibians & Reptiles: x 7841 (office) x 7970 (wet lab); rgkamei@fieldmuseum.org
2. Josh Mata, Assistant Collections Manager, Amphibians & Reptiles: x 7494; jmata@fieldmuseum.org

**Comment by lhancockFM** [comment]
Anthro:
Laure Dussubieux
Gary Feinman
William Parkinson
Ryan Williams
Foreman Bandama
Christina Friberg
Elspeth Geiger
Alaka Wali
Helen Robbins
Drew Jepson
June Carpenter
Lauren Hancock
Elana Dux
Emma Turner-Trujillo
Christopher Philipp
Stacy Drake
Jamie Kelly
Michelle Brownlee
JP Brown
Erin Murphy
J. Kae Goodbear
Nicole Schmidt
Dan Kaping
Cass Gero
Julia Kennedy
Sam Frank
Emily Starck
